FROM golang:1.26-alpine AS dev

WORKDIR /app

RUN apk add --no-cache wget

RUN go install github.com/air-verse/air@latest

COPY go.mod go.sum ./
RUN go mod download

COPY . .

EXPOSE 8080

CMD ["air", "-c", ".air.toml"]

FROM golang:1.26-alpine AS builder

WORKDIR /app

COPY go.mod go.sum ./
RUN go mod download

COPY . .

RUN CGO_ENABLED=0 GOOS=linux go build -o /bin/optistock-api ./cmd/server

FROM gcr.io/distroless/static-debian12 AS prod

WORKDIR /

COPY --from=builder /bin/optistock-api /optistock-api
COPY migrations /migrations

EXPOSE 8080

ENTRYPOINT ["/optistock-api"]
